services:
  backend:
    # Pull from GitHub Container Registry
    image: ghcr.io/steelburn/dockety-backend:latest
    container_name: dockety_backend
    volumes:
      # Mount the Docker socket to allow the backend to manage Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist the SQLite database
      - dockety_data:/app/data
    restart: unless-stopped

  frontend:
    # Pull from GitHub Container Registry
    image: ghcr.io/steelburn/dockety-frontend:latest
    container_name: dockety_frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  dockety_data:
